# Generated by Django 5.0 on 2023-12-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cheftable", "0002_alter_menus_category_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("reservation_day", models.CharField(max_length=50)),
                ("seats", models.IntegerField()),
            ],
        ),
    ]
